SEPARATOR  TAB
AVERAGEFREQ ON
SCHEME SAMPLESIZE

# unique_id       CHR     POS     EFFECT_ALLELE   NON_EFFECT_ALLELE       EAF     BETA    SE      PVALUE  INFO    HWE     N       MAC

MARKER unique_id
ALLELE EFFECT_ALLELE NON_EFFECT_ALLELE
FREQ EAF
WEIGHT N
EFFECT BETA
PVALUE PVALUE

PROCESS NEO_lffev1_smk_chr1_22_filtered.txt.gz
PROCESS NEO_lffev1_nonsmk_chr1_22_filtered.txt.gz

OUTFILE NEO_FEV1_ .tbl
ANALYZE
QUIT
