SEPARATOR  TAB
AVERAGEFREQ ON
SCHEME SAMPLESIZE

# unique_id       CHR     POS     EFFECT_ALLELE   NON_EFFECT_ALLELE       EAF     BETA    SE      PVALUE  INFO    HWE     N       MAC

MARKER unique_id
ALLELE EFFECT_ALLELE NON_EFFECT_ALLELE
FREQ EAF
WEIGHT N
EFFECT BETA
PVALUE PVALUE

PROCESS NEO_lffevfvcc_smk_chrX_filtered.txt.gz
PROCESS NEO_lffevfvcc_nonsmk_chrX_filtered.txt.gz

OUTFILE NEO_FF_CHRX_ .tbl
ANALYZE
QUIT
