SEPARATOR  TAB
AVERAGEFREQ ON
SCHEME SAMPLESIZE

# unique_id       SNPID   CHR     BP      GENPOS  ALLELE1 ALLELE0 A1FREQ  F_MISS  CHISQ_LINREG    P_LINREG        BETA    SE      CHISQ_BOLT_LMM_INF      P_BOLT_LMM_INF  Rsq     sample_size     MAC

MARKER unique_id
ALLELE ALLELE1 ALLELE0
FREQ A1FREQ
WEIGHT sample_size
EFFECT BETA
PVALUE P_BOLT_LMM_INF

PROCESS hunt_FEV1FVC_smk_chr1-23_filtered.txt.gz
PROCESS hunt_FEV1FVC_nonsmk_chr1-23_filtered.txt.gz

OUTFILE hunt_FF_ .tbl
ANALYZE
QUIT
