SEPARATOR  TAB
AVERAGEFREQ ON
SCHEME SAMPLESIZE

# unique_id       SNP     REF     ALT     CHROM   POS     N_INFORMATIVE   AF      U       V       STAT    DIRECTION       EFFECT  SE      PVALUE  Rsq     MAC

MARKER unique_id
ALLELE ALT REF
FREQ AF
WEIGHT N_INFORMATIVE
EFFECT EFFECT
PVALUE PVALUE

PROCESS	ARIC_FEV1_smk_CHR1_22_filtered.txt.gz
PROCESS ARIC_FEV1_nonsmk_CHR1_22_filtered.txt.gz

OUTFILE ARIC_EA_FEV1_ .tbl
ANALYZE
QUIT
